---
title: "Clinical Pharmacology of Tafenoquine for the radical cure of vivax malaria"
author: "James Watson"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = T, cache.comments = FALSE,
                      echo = F, include = TRUE, 
                      fig.width = 8, fig.height = 8,
                      fig.pos = 'H',dev = 'png', dpi = 300)
library(mgcv)
library(haven)
library(sjlabelled)
library(gtools)
library(lme4)
```


# Preambule
## Load data

```{r load_data}
# WWARN collated baseline and outcome data
outcome_dat = read_dta('an1_tq_efficacy.dta')
outcome_dat$study = 
  plyr::mapvalues(outcome_dat$sid, 
                  from = c('BSAJK','KTMTV','PRSXC'),
                  to = c('GATHER',
                         'DETECTIVE_Ph3',
                         'DETECTIVE_Ph2'))
# remove patients who took primaquine
outcome_dat = outcome_dat[is.na(outcome_dat$pqmgkgtot),]
outcome_dat$AMT = round(outcome_dat$weight*outcome_dat$tqmgkgtot)
writeLines('DTQ doses in data:')
table(outcome_dat$AMT)

## PK summaries statistics from Joel
pk_summaries = read.csv('TQ_PK_summaries.csv')

# CYP2D6 genotyping
cyp2d6 = read.csv('CYP2D6.csv')
outcome_dat = merge(outcome_dat, cyp2d6, by = 'pid', all.x = T)

# Methaemoglobin: removed all measurements taken at/after recurrence
mthb_dat = read.csv('Methb_long.csv')
mthb_dat = merge(mthb_dat, outcome_dat[, c('pid','tqmgkgtot','country')],by='pid')
outcome_dat = merge(outcome_dat, pk_summaries, 
                    by.x = 'pid', by.y = 'PID', all.x = T)

outcome_dat$log_AUC = log(outcome_dat$AUC)
outcome_dat$AUC = outcome_dat$AUC/1000
```


# Data summaries 


```{r data_summaries}
table(outcome_dat$country)

xx = aggregate(hgbmet ~ pid, data = mthb_dat, length)
writeLines(sprintf('Median number of methb measurements is %s',median(xx$hgbmet)))
print(range(xx$hgbmet))

table(outcome_dat$outcome7to180)
xx=aggregate(outcome7to180 ~ AMT, data = outcome_dat, FUN = function(x) c(round(100*mean(x),1), length(x)))
colnames(xx$outcome7to180)=c('Rec 6 mths (%)', 'n')
colnames(xx)[1]='Dose (mg)'; colnames(xx)[2]=''
print(xx)
```


CYP2D6

```{r}
table(outcome_dat$CYP2D6, outcome_dat$CYP2D6AS)
diplotypes = strsplit(outcome_dat$CYP2D6, split = '/')

round(100*table(unlist(diplotypes))/sum(table(unlist(diplotypes))),1)

# THIS NEEDS CHECKING
ASscore_key = data.frame(name=c('*1', '*10', '*2', '*36', '*39', '*4', '*5', '*3', '*6', '*9', '*17', '*41'),
                         score=c(1,   0.25,   1,     0,     1,    0,     0,   0.5,  0.5,  0.5,  0.5,   0.5))

# Make updated AS score
outcome_dat$AS_score = NA
for(i in 1:nrow(outcome_dat)){
  if(!is.na(outcome_dat$CYP2D6AS[i])){
    my_dp = diplotypes[[i]]
    outcome_dat$AS_score[i] =
      ASscore_key$score[which(ASscore_key$name == my_dp[1])]+
      ASscore_key$score[which(ASscore_key$name == my_dp[2])]
  }
}

table(outcome_dat$AS_score, outcome_dat$CYP2D6AS)
```


## Basic data plots

weight

```{r weight_plot}
ind = (outcome_dat$AMT==300)
fail_rates = aggregate(outcome7to180 ~ country, outcome_dat[ind, ], 
                       function(x) c(round(100*mean(x)), length(x)))
print(fail_rates)
fail_rates_all = aggregate(outcome7to180 ~ country, outcome_dat, 
                           function(x) c(round(100*mean(x)), length(x)))
print(fail_rates_all)
par(las=1, family='serif', cex.lab=1.3, cex.axis=1.3, mfrow=c(3,3))
for(cc in unique(outcome_dat$country)){
  hist(outcome_dat$weight[outcome_dat$country==cc],main=cc,xlab='kg',
       breaks = seq(30, 140, by=5))
}
outcome_dat$studysite = as.factor(outcome_dat$studysite)
table(outcome_dat$AMT)

ind_sensitivity = outcome_dat$AMT >= 300
sum(ind_sensitivity)
```




```{r methaemoglobin}
mthb_mat = array(dim = c(length(unique(mthb_dat$pid)),30))
rownames(mthb_mat) = unique(mthb_dat$pid)

for(i in 1:nrow(mthb_mat)){
  ind = mthb_dat$pid==rownames(mthb_mat)[i]
  f_mthb = approxfun(x = mthb_dat$dayofobs[ind], y = mthb_dat$hgbmet[ind])
  mthb_mat[i, ] = f_mthb(0:29)
}

par(las=1, mfrow=c(2,2), cex.lab=1.5, cex.axis=1.5)
for(cc in unique(outcome_dat$tqcat)){
  ids = unique(outcome_dat$pid[outcome_dat$tqcat==cc])
  plot(0:29, colMeans(mthb_mat[rownames(mthb_mat) %in% ids, ],na.rm = T),
       type='l',lwd=3, ylim = c(0, 8), ylab='Methaemoglobin (%)',
       xlab='Days since dose',
       panel.first=grid(), main=cc)
  lines(0:29, apply(mthb_mat[rownames(mthb_mat) %in% ids, ],2, quantile, probs=.1, na.rm = T))
  lines(0:29, apply(mthb_mat[rownames(mthb_mat) %in% ids, ],2, quantile, probs=.9, na.rm = T))
}


day_7_mthb = data.frame(pid = rownames(mthb_mat), day7_mthb=mthb_mat[,8])
write.csv(x = day_7_mthb, file = 'day_7_mthb.csv')
outcome_dat = merge(outcome_dat, day_7_mthb, by='pid', all.x=T)

par(las=1, mfrow=c(1,1))
plot(outcome_dat$tqmgkgtot, log10(outcome_dat$day7_mthb), yaxt='n',
     ylab='Day 7 methaemoglobin (%)', xlab='Tafenoquine dose (mg/kg)',
     panel.first=grid())
axis(2, at = -1:1, labels = 10^(-1:1))
axis(2, at = log10(seq(0.1, 1, by=.1)), labels = NA)
axis(2, at = log10(seq(1, 10, by=1)), labels = NA)
mod_day7 = lm(log10(day7_mthb) ~ tqmgkgtot, data=outcome_dat)
lines(0:15, predict(mod_day7, data.frame(tqmgkgtot=0:15)),lty=2,lwd=3)
mod_day7 = gam(log10(day7_mthb) ~ s(tqmgkgtot,k=3), data=outcome_dat)
lines(0:15, predict(mod_day7, data.frame(tqmgkgtot=0:15)),lty=2,lwd=3)


mod_day7_2 = lm(day7_mthb ~ tqmgkgtot + scale(AUC),
                data=outcome_dat[outcome_dat$AMT>100, ])
summary(mod_day7_2)



outcome_dat$t_12_terminal[outcome_dat$t_12_terminal>35]=NA
outcome_dat$t_12_alpha[outcome_dat$t_12_alpha>4]=NA

mod_day7_3 = lm(log10(day7_mthb) ~ tqmgkgtot + t_12_terminal,
                data=outcome_dat)
summary(mod_day7_3)
mod_day7_4 = lm(log10(day7_mthb) ~ tqmgkgtot + t_12_alpha,
                data=outcome_dat)
summary(mod_day7_4)
mod_day7_3 = MASS::rlm(log10(day7_mthb) ~ tqmgkgtot + t_12_terminal,
                       data=outcome_dat)
plot(outcome_dat$t_12_terminal, log10(outcome_dat$day7_mthb),
     xlab='Terminal elimination half life (days)', ylab = 'Day 7 methaemoglobin (%)',
     panel.first=grid(), yaxt='n')
axis(2, at = -1:1, labels = 10^(-1:1))
axis(2, at = log10(seq(0.1, 1, by=.1)), labels = NA)
axis(2, at = log10(seq(1, 10, by=1)), labels = NA)
lines(5:30, predict(mod_day7_3, data.frame(tqmgkgtot=5, t_12_terminal=5:30)),lwd=3)
```



```{r mgkg_AUC}
par(las=1, cex.axis=1.3, cex.lab=1.3)
plot(outcome_dat$tqmgkgtot, outcome_dat$AUC,
     xlab='TQ (mg/kg)',col=as.numeric(ind_sensitivity)+1,
     ylab = 'TQ AUC (rescaled)', panel.first=grid())
mod = gam(AUC ~ s(tqmgkgtot,k=4), data = outcome_dat)
lines(0:14, predict(mod, data.frame(tqmgkgtot=0:14)),lwd=3, col='darkblue')
```



```{r terminal_half_life}
par(las=1, cex.axis=1.3, cex.lab=1.3)
hist(pk_summaries$t_12_terminal, xlim = c(0,30),
     xlab='Terminal elimination half life (days)', breaks = 30,main='',
     yaxt='n',ylab='')
median(pk_summaries$t_12_terminal)
```



# Weight based models of tafenoquine efficacy


```{r models1}
mod_mgkg_all = glmer(outcome7to180 ~ tqmgkgtot + logpara0 + (1|studysite),
                     family='binomial', 
                     data = outcome_dat)
mod_mgkg_all_out = summary(mod_mgkg_all)
print(mod_mgkg_all_out$coefficients)
writeLines(sprintf('Using all data (n=%s), the odds ratio for recurrence at 6 months for each additional mg/kg of tafenoquine is %s (95%% CI %s to %s)',
                   length(mod_mgkg_all_out$residuals),
                   round(exp(fixef(mod_mgkg_all)['tqmgkgtot']),2),
                   round(exp(mod_mgkg_all_out$coefficients['tqmgkgtot',1:2]%*%c(1,-1.96)),2),
                   round(exp(mod_mgkg_all_out$coefficients['tqmgkgtot',1:2]%*%c(1,1.96)),2)))

mod_mgkg_sens = glmer(outcome7to180 ~ tqmgkgtot + logpara0 + (1|studysite),
                      family='binomial', data = outcome_dat[ind_sensitivity, ])
mod_mgkg_sens_out = summary(mod_mgkg_sens)
print(mod_mgkg_sens_out$coefficients)
writeLines(sprintf('Using patients who got 300 or 600 mg (n=%s), the odds ratio for recurrence at 6 months for each additional mg/kg of tafenoquine is %s (95%% CI %s to %s)',
                   length(mod_mgkg_sens_out$residuals),
                   round(exp(fixef(mod_mgkg_sens)['tqmgkgtot']),2),
                   round(exp(mod_mgkg_sens_out$coefficients['tqmgkgtot',1:2]%*%c(1,-1.96)),2),
                   round(exp(mod_mgkg_sens_out$coefficients['tqmgkgtot',1:2]%*%c(1,1.96)),2)))



# mod_glm_auc = glmer(outcome7to180 ~ scale(AUC) + logpara0 + (1|studysite),
#                     family='binomial', data = outcome_dat[ind_sensitivity, ])
# summary(mod_glm_auc)
# exp(fixef(mod_glm_auc)['scale(AUC)'])
# 
# mod_glm_t_12 = glmer(outcome7to180 ~ t_12_terminal + logpara0 + (1|studysite),
#                     family='binomial', data = outcome_dat[ind_sensitivity, ])
# summary(mod_glm_t_12)
# exp(fixef(mod_glm_t_12)['t_12_terminal'])
# 
# mod_glm_t_12_tq = glmer(outcome7to180 ~ tqmgkgtot + t_12_terminal + logpara0 + (1|studysite),
#                     family='binomial', data = outcome_dat)
# summary(mod_glm_t_12_tq)
# exp(fixef(mod_glm_t_12_tq)['t_12_terminal'])
# 
# mod_glm_everything = glmer(outcome7to180 ~ tqmgkgtot + t_12_terminal + day7_mthb + (1|studysite),
#                     family='binomial', data = outcome_dat)
# summary(mod_glm_everything)
# exp(fixef(mod_glm_t_12_tq)['t_12_terminal'])
# 
# 
# mod_glm_mthb1 = glmer(outcome7to180 ~ day7_mthb + tqmgkgtot + logpara0 + (1|studysite),
#                       family='binomial',data = outcome_dat)
# summary(mod_glm_mthb1)
# 
# mod_glm_mthb2 = glmer(outcome7to180 ~ day7_mthb + tqmgkgtot + AUC + logpara0 + (1|studysite),
#                       family='binomial',data = outcome_dat)
# summary(mod_glm_mthb2)
# 
# 
# 
# mod_gam = gam(outcome7to180 ~ s(tqmgkgtot) + logpara0 + s(studysite,bs = 're'),
#               family='binomial',
#               data = outcome_dat[ind_sensitivity,])
# summary(mod_gam)
# 
# 
# mod_gam_all = gam(outcome7to180 ~ s(tqmgkgtot) +
#                     logpara0 + s(studysite,bs = 're'),
#                   family='binomial',
#                   data = outcome_dat)
# summary(mod_gam_all)
# 
# mod_gam_auc = gam(outcome7to180 ~ s(AUC, k=4) +
#                     logpara0 + s(studysite,bs = 're'),
#                   family='binomial',
#                   data = outcome_dat)
# summary(mod_gam_auc)
# 
# 
# ## 4 month endpoint
# ind_4months = outcome_dat$dlast >= 120 | (!is.na(outcome_dat$malariaday) & outcome_dat$malariaday<120)
# mod_glm_all_100 = glmer(outcome7to180 ~ tqmgkgtot + (1|studysite),
#                         family='binomial', data = outcome_dat[ind_4months, ])
# summary(mod_glm_all_100)
# exp(fixef(mod_glm_all_100)['tqmgkgtot'])
# 
# 
# ind_lfup = (is.na(outcome_dat$malariaday) | outcome_dat$malariaday> 180)
# par(las=1)
# hist(outcome_dat$dlast[ind_lfup],main='', breaks = seq(0, 220, by=10),
#      xlab='Day of last follow-up')
```



main mg/kg plot

```{r mg_kg_efficacy}
par(las=1, cex.lab=1.5, cex.axis=1.5,mar=c(0,5,2,2))
layout(mat = matrix(c(1,2,2,2),nrow = 4))
hist(outcome_dat$tqmgkgtot,
     ylab='',xaxt='n',xlab='',yaxt='n',
     main='', breaks = seq(0,15,by=.5))

xs1=seq(2.5,14,length.out=100)
y_preds1 = predict(mod_glm, newdata = data.frame(tqmgkgtot=xs1,
                                                 logpara0=4,
                                                 studysite = -1,
                                                 country = -1),
                   se.fit = T, re.form=NA)
y_preds1_gam = predict(mod_gam, newdata = data.frame(tqmgkgtot=xs1,
                                                     logpara0=4,
                                                     studysite = -1,
                                                     country = -1),
                       se.fit = T, re.form=NA)

xs_all=seq(0,15,length.out=100)
y_preds_all = predict(mod_glm_all, newdata = data.frame(tqmgkgtot=xs_all,
                                                        logpara0=4,
                                                        studysite = -1,
                                                        country = -1),
                      se.fit = T, re.form=NA)
y_preds_all_gam = predict(mod_gam_all, newdata = data.frame(tqmgkgtot=xs_all,
                                                            logpara0=4,
                                                            studysite = -1,
                                                            country = -1),
                          se.fit = T, re.form=NA)

par(las=1, cex.lab=1.5, cex.axis=1.5,mar=c(5,5,0,2))
plot(xs1, 100*inv.logit(y_preds1_gam$fit), type='l',lwd=3, 
     xlab = 'Single dose tafenoquine (mg/kg)',
     ylab = 'Recurrent P. vivax within 6 months (%)', 
     ylim = c(0,70), panel.first=grid(), xaxt='n',
     xlim = c(0,15))
polygon(x = c(xs1, rev(xs1)),
        y = 100*inv.logit(c(y_preds1_gam$fit+1.96*y_preds1_gam$se.fit,
                            rev(y_preds1_gam$fit-1.96*y_preds1_gam$se.fit))),
        border = NA, col = adjustcolor('grey', .4))

axis(1, at = c(0,5,10,15))
# lines(xs1, 100*inv.logit(y_preds1))

# lines(xs, 100*inv.logit(y_preds1_gam$fit),col='red')
lines(xs_all, 100*inv.logit(y_preds_all_gam$fit),col='red',lwd=3)
polygon(x = c(xs_all, rev(xs_all)),
        y = 100*inv.logit(c(y_preds_all_gam$fit+1.96*y_preds_all_gam$se.fit,
                            rev(y_preds_all_gam$fit-1.96*y_preds_all_gam$se.fit))),
        border = NA, col = adjustcolor('red', .2))
# abline(v=4.8, lwd=2, lty=2)


```



second mg/kg plot

```{r mg_kg_efficacy_all}
par(las=1, cex.lab=1.5, cex.axis=1.5,mar=c(0,5,2,2))
layout(mat = matrix(c(1,2,2,2),nrow = 4))
hist(outcome_dat$tqmgkgtot,ylab='',xaxt='n',xlab='',yaxt='n',
     main='', breaks = seq(0,14.5,by=.5))

xs2=seq(0,14.5,length.out=100)
y_preds2 = predict(mod_gam_all, newdata = data.frame(tqmgkgtot=xs2,
                                                     logpara0=4,
                                                     studysite = -1),
                   se.fit = T)

par(las=1, cex.lab=1.5, cex.axis=1.5,mar=c(5,5,0,2))
plot(xs2, 100*inv.logit(y_preds2$fit), type='l',lwd=3, 
     xlab = 'Single dose tafenoquine (mg/kg)',
     ylab = 'Recurrent P. vivax within 6 months (%)', 
     ylim = c(0,70), panel.first=grid(), xaxt='n')
axis(1, at = c(2,5,9,12))
polygon(x = c(xs2, rev(xs2)), 
        y = 100*inv.logit(c(y_preds2$fit+1.96*y_preds2$se.fit, 
                            rev(y_preds2$fit-1.96*y_preds2$se.fit))),
        border = NA, col = adjustcolor('grey', .4))
abline(v=4.8, lwd=2, lty=2)
lines(xs1,100*inv.logit(y_preds1),lwd=3, col='red')

```



vomiting

```{r}
mod_vom = glmer(vomiting ~ tqmgkgtot + (1|studysite),
                family='binomial', data = outcome_dat)
summary(mod_vom)
```


```{r revised_dosing}
f_weight = function(w_kg, w_doses, w_cuts){
  out=w_doses[as.numeric(cut(x = w_kg, 
                             breaks = w_cuts,
                             include.lowest=T))]
  return(out)
}

w_cuts_standard = c(10, 20, 35, 150)
w_dose_standard = c(100, 200, 300)

w_cuts_revised = c(10, 15,  20,  30,   45,  60, 80, 150)
w_dose_revised = c(  150, 200, 250, 300, 450, 600, 750)

xs=seq(10,100,length.out=1000)
par(las=1, cex.lab=1.5, cex.axis = 1.5, mar=c(0,5,2,2))
layout(mat = matrix(c(1,2,2,2,2)))
hist(outcome_dat$weight,main='',yaxt='n', ylab='',
     xlim = range(xs), breaks = seq(10,150,by=5), xaxt='n',xlab='')
par(mar=c(5,5,0,2))
plot(xs, f_weight(xs, w_doses = w_dose_standard, 
                  w_cuts = w_cuts_standard)/xs,
     type='l',lwd=3,panel.first = grid(),ylim = c(0,15),
     xlab='Weight (kg)', ylab = 'Tafenoquine mg/kg dose',
     xaxt='n')
axis(1, at = union(w_cuts_standard, w_cuts_revised))
# lines(45:100, rep(median(f_weight(45:100, w_doses = w_dose_standard, w_cuts = w_cuts_standard)/45:100), 56),lwd=2)
lines(xs, f_weight(xs, w_doses = w_dose_revised, w_cuts = w_cuts_revised)/xs, lwd=3, lty=2,col='red')
# lines(45:100, rep(median(f_weight(45:100, w_doses = w_dose_revised,
# w_cuts = w_cuts_revised)/45:100),56),
# lty=2,col='red',lwd=2)

lines(45:100, 450/(45:100),lty=3,col='red',lwd=2)
lines(45:100, 600/(45:100),lty=3,col='red',lwd=2)

legend('topright', lwd=3, lty=1:2, col=1:2,
       legend = c('Current','Revised'), cex=1.5,
       title = 'Dose', inset=0.03)

text(x=w_cuts_revised[1:7], 
     y = rep(c(.3,.6),4)[1:7]+
       f_weight(w_cuts_revised[1:7]+2,
                w_doses = w_dose_revised, 
                w_cuts = w_cuts_revised)/w_cuts_revised[1:7],
     labels = paste0(w_dose_revised[1:7],'mg'), cex=1, col = 'red')

text(x=w_cuts_standard[1:3]+2, 
     y = 4,cex=1, col = 'black',
     labels = paste0(w_dose_standard[1:3],'mg'))

sim_ws = sample(outcome_dat$weight, size = 10^5, replace = T)
sim_dose_mgkg_current = f_weight(w_kg = sim_ws, w_doses = w_dose_standard, w_cuts = w_cuts_standard)/sim_ws
sim_dose_mgkg_revised = f_weight(w_kg = sim_ws, w_doses = w_dose_revised, w_cuts = w_cuts_revised)/sim_ws


sim_rec_current = predict(mod_gam_all, 
                          newdata = data.frame(tqmgkgtot=sim_dose_mgkg_current,
                                               logpara0=4,
                                               studysite = -1),re.form=NA,
                          type='response')

sim_rec_revised = predict(mod_gam_all, 
                          newdata = data.frame(tqmgkgtot=sim_dose_mgkg_revised,
                                               logpara0 = 4,
                                               studysite = -1),re.form=NA,
                          type='response')

sim_450 = predict(mod_gam_all, 
                  newdata = data.frame(tqmgkgtot=450/sim_ws[sim_ws>=45],
                                       logpara0 = 4,
                                       studysite = -1),re.form=NA,
                  type='response')

sim_600 = predict(mod_gam_all, 
                  newdata = data.frame(tqmgkgtot=600/sim_ws[sim_ws>=45],
                                       logpara0 = 4,
                                       studysite = -1),re.form=NA,
                  type='response')


writeLines(sprintf('Under the current dosing the mean recurrence proportion within 6 months is %s%%', round(100*mean(sim_rec_current),1)))


writeLines(sprintf('Under the revised dosing the mean recurrence proportion within 6 months is %s%%', round(100*mean(sim_rec_revised),1)))


writeLines(sprintf('If all adults>45 kg get 450 mg the mean recurrence proportion within 6 months is %s%%', round(100*mean(sim_450),1)))

writeLines(sprintf('If all adults>45 kg get 600 mg the mean recurrence proportion within 6 months is %s%%', round(100*mean(sim_600),1)))
```



# Power calculations 


Superiority of 450 over 300 mg single dose

```{r power_calc}
Ns = seq(50, 350, by = 50)
Sims = 1000
doses = c(450, 600)
power_mat = array(dim = c(length(Ns), Sims, length(doses)))
options(warn= -1)

for(d in 1:length(doses)){
  for(i in 1:length(Ns)){
    for(j in 1:Sims){
      trts = c(rep(300, Ns[i]), rep(doses[d], Ns[i]))
      ws = sample(outcome_dat$weight, size = 2*Ns[i], replace = T)
      sim_out = predict(mod_gam_all, 
                        newdata = data.frame(tqmgkgtot=trts/ws,
                                             logpara0 = 4,
                                             studysite = -1),
                        re.form=NA,
                        type='response')
      outcomes = rbinom(n = 2*Ns[i], size = 1, prob = sim_out)
      x_test = fisher.test(table(trts, outcomes))
      power_mat[i,j,d]=as.numeric(x_test$p.value<0.025 & x_test$estimate<1)
    }
  }
}

par(las=1, family='serif', cex.lab=1.3, cex.axis=1.3)
plot(2*Ns, 100*rowMeans(power_mat[,,1]), type='b', ylim = c(0,100),panel.first=grid(),
     xlab= 'Sample size (total, 1:1 randomisation)', ylab = 'Power %',lwd=2)
lines(2*Ns, 100*rowMeans(power_mat[,,2]),type='b',lwd=2,lty=2)
legend('bottomright', lty=1:2, legend = c('450 mg', '600 mg'),lwd=2,inset=0.03)
```

